name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Self-hosted runner is specified here
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3

      - name: Set up Python
        uses: actions/setup-python@v3  # Updated to v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyscaffold
          pip install tox

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        if: |
          contains(github.event.head_commit.message, '#minor') ||
          contains(github.event.head_commit.message, '#patch') ||
          contains(github.event.head_commit.message, '#major')
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          release_branches: main
          DEFAULT_BUMP: patch
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Run tests and build package
        run: |
          tox  # This will run tests defined in tox
          tox -e docs  # Build documentation
          tox -e build  # Build the package

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./docs/_build/html  # Ensure this directory is correct
